### ISSUE TITLE
Please bump golang.org/x/sys to v0.5.0

### ISSUE THREAD

**Issue by clausecker** [diamondburned/gotktrix#42]
The port currently depends on `golang.org/x/sys@v0.0.0-20210615035016-665e8c7367d1`.  This version fails to build on riscv64 FreeBSD 13.1:

```
# golang.org/x/sys/unix
vendor/golang.org/x/sys/unix/sockcmsg_unix.go:34:9: undefined: Cmsghdr
vendor/golang.org/x/sys/unix/syscall_freebsd.go:54:9: undefined: RawSockaddrDatalink
vendor/golang.org/x/sys/unix/syscall_unix.go:186:38: undefined: _Socklen
vendor/golang.org/x/sys/unix/syscall_unix.go:193:7: undefined: RawSockaddrInet4
vendor/golang.org/x/sys/unix/syscall_unix.go:201:9: undefined: RawSockaddrInet6
vendor/golang.org/x/sys/unix/syscall_unix.go:207:7: undefined: RawSockaddrUnix
vendor/golang.org/x/sys/unix/cap_freebsd.go:19:23: undefined: CAP_RIGHTS_VERSION_00
vendor/golang.org/x/sys/unix/cap_freebsd.go:20:23: undefined: CAP_RIGHTS_VERSION_00
vendor/golang.org/x/sys/unix/cap_freebsd.go:47:21: undefined: CapRights
vendor/golang.org/x/sys/unix/cap_freebsd.go:51:24: undefined: CapRights
vendor/golang.org/x/sys/unix/cap_freebsd.go:51:24: too many errors
```

Please bump the dependency to `v0.5.0` to fix the build.
